### ISSUE TITLE
Package Name Conflict

### ISSUE THREAD

**Issue by xloem** [moskomule/memory_efficient_attention.pytorch#1]
Hey, thanks for your incredible work helping us understand this optimization.

There's another project on pipy that has this same name: https://github.com/AminRezaei0x443/memory-efficient-attention . Would you be willing to change the name of your project in setup.cfg, maybe appending 'pytorch', so both implementations can be installed side-by-side and compared?

I'm still learning this algorithm myself, and was surprised that pip wouldn't install both packages to use and inspect them next to each other.

**Comment by moskomule** [comment]
Hi, why not just clone the repository,  change the name as you like, and then install by `pip install -e .`?

**Comment by xloem** [comment]
Well yes I changed things locally. I thought you might be unaware of the other project and could want to have a package name that could be uploaded to pypi and used as a dependency in other projects.

I noticed when I pip install it doesn't actually install the python file yet, hadn't noticed that when I opened the issue :)

Thanks for your efforts here helping us.
